name: E2E tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
      - name: tests
        if: env.GIT_DIFF
        run: make test-e2e
